//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsciiSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsciiSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Expected token &apos;{0}&apos; is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ADS0001_ExpectedToken {
            get {
                return ResourceManager.GetString("ADS0001_ExpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Section title text is missing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ADS0002_MissingSectionTitleText {
            get {
                return ResourceManager.GetString("ADS0002_MissingSectionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must not be equal to the specified value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentEqual {
            get {
                return ResourceManager.GetString("Error_ArgumentEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentGreaterThan {
            get {
                return ResourceManager.GetString("Error_ArgumentGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too large. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("Error_ArgumentGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too small. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentLessThan {
            get {
                return ResourceManager.GetString("Error_ArgumentLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too small. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentLessThanOrEqual {
            get {
                return ResourceManager.GetString("Error_ArgumentLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must not be negative. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentNegative {
            get {
                return ResourceManager.GetString("Error_ArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be positive. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentNegativeOrZero {
            get {
                return ResourceManager.GetString("Error_ArgumentNegativeOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be equal to the required value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentNotEqual {
            get {
                return ResourceManager.GetString("Error_ArgumentNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value cannot be null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_ArgumentNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value cannot be null or white space. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Error_ArgumentNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must not be zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_ArgumentZero {
            get {
                return ResourceManager.GetString("Error_ArgumentZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum nesting level exceeded. Document structure is too deeply nested. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error_NestingLevelExceeded {
            get {
                return ResourceManager.GetString("Error_NestingLevelExceeded", resourceCulture);
            }
        }
    }
}
